name: Slack

on:
  push:
    branches: ["feature/slack"]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Set up python
          uses: actions/setup-python@v3
          with:
            python-version: "3.12"
        - name: Build image
          run: docker build . -t my/python_image
          working-directory: slack
        - name: Run container
          run: docker run --entrypoint bash --name slack -v ${PWD}:/app my/python_image
          working-directory: slack
